# Generated by Django 4.1.1 on 2022-11-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0002_address_rentalstation"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="adresse",),
        migrations.RemoveField(model_name="client", name="pays",),
        migrations.RemoveField(model_name="client", name="telephone",),
        migrations.RemoveField(model_name="client", name="ville",),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rent.address",
            ),
        ),
    ]
