# Generated by Django 4.1.1 on 2022-11-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0003_remove_client_adresse_remove_client_pays_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="telephone",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
