-- Database: bootcamp
---- 1-2-3
-- CREATE TABLE students(
-- 		id SERIAL PRIMARY KEY,
--  	first_name VARCHAR (50) NOT NULL,
--  	last_name VARCHAR (100) NOT NULL,
-- 		birth_date DATE NOT NULL
-- );

-- INSERT INTO students(first_name,last_name,birth_date)
-- VALUES
-- 	('Marc','Benichou','02/11/1998'),
-- 	('Yoan','Cohen','03/12/2010'),
-- 	('Lea','Benichou','27/07/1987'),
-- 	('Amelia','Dux','07/04/1996'),
-- 	('David','Grez','14/06/2003'),
-- 	('Omer','Simpson','03/10/1980'),
-- 	('Steve','Sankara','10/06/2000');
--
-- 1
-- SELECT * FROM students
-- 2
-- SELECT * FROM students WHERE last_name = 'Benichou' AND first_name = 'Marc';
-- 3 
-- SELECT * FROM students WHERE last_name = 'Benichou' OR first_name = 'Marc';
-- 4
--SELECT * FROM students WHERE first_name LIKE '%a%';
-- 5
-- SELECT * FROM students WHERE first_name ILIKE 'a%';
-- 6
-- SELECT * FROM students WHERE first_name LIKE '%a';
-- 7
-- SELECT * FROM students WHERE first_name LIKE '%a_';
-- 8
-- SELECT * FROM students WHERE id = 1 OR id = 3;

---- 4
SELECT * FROM students WHERE birth_date >= '01/01/2000';