# Generated by Django 4.1.6 on 2023-02-07 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_avis_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 8, 21, 20, 723798)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 7, 8, 21, 20, 723798)),
        ),
    ]
